### ISSUE TITLE
Conflict with tree-sitter package

### ISSUE THREAD

**Issue by jotafarias13** [douglasdavis/numpydoc.el#14]
Hey, there!

I've been using this package for a while now and it is very handy and useful for me.
Recently I installed [tree-sitter](https://github.com/emacs-tree-sitter/elisp-tree-sitter) in Emacs and began seeing a strange behavior with my docstring generation.

When tree-sitter is enabled and I run `numpydoc-generate`, it creates the docs but yasnippet completion is disabled. At the same time, my syntax highlighting goes crazy and I have to kill the buffer and open it again to get back to normal. If I undo the doc generation and try again, I get yasnippet completion but the syntax highlighting still goes crazy.

Running `numpydoc-generate` once:
![numpydoc_once](https://user-images.githubusercontent.com/80363136/232177644-ca444d6d-ba05-424e-b36d-07cf6b240c18.jpg)

Running `numpydoc-generate` twice:
![numpydoc_twice](https://user-images.githubusercontent.com/80363136/232177650-02b3bfff-39c4-490c-8458-6501c870c9a6.jpg)

Do you have any idea if this is a problem with numpydoc package? I don't write docstring very often so it doesn't get in the way that much. But I would really like to be able to use both packages without conflict.

Two minimal configurations are attached. One without tree-sitter (numpydoc works fine) and one with tree-sitter (numpydoc showing weird behavior).

Minimal configuration that works fine:
![numpydoc_working](https://user-images.githubusercontent.com/80363136/232177354-5d5bdb0f-4c8f-4470-abf9-7cb6533814a8.jpg)

Minimal configuration with described behavior:
![numpydoc_treesitter](https://user-images.githubusercontent.com/80363136/232177363-275f7f08-4c0c-4ff7-ba99-9d3b7a6a7719.jpg)

Below are the minimal configurations depicted.

Minimal configuration that works fine:
```
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

(use-package python
  :init
  (setq python-indent-guess-indent-offset nil)
  :config
  (setq python-shell-interpreter "python"))

(use-package numpydoc
  :after yasnippet
  :init
  (setq numpydoc-insertion-style nil)
  (setq numpydoc-insertion-style 'yas)
  (setq numpydoc-insert-examples-block nil)
  :bind (:map python-mode-map
	      ("C-c C-n" . numpydoc-generate))
  :after python)

(use-package yasnippet
  :config (yas-global-mode 1))
(use-package yasnippet-snippets)
(setq yas-snippet-dirs '("~/.emacs.d/snippets"))
```

Minimal configuration with described behavior:
```
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

(use-package python
  :init
  (setq python-indent-guess-indent-offset nil)
  :config
  (setq python-shell-interpreter "python"))

(use-package numpydoc
  :after yasnippet
  :init
  (setq numpydoc-insertion-style nil)
  (setq numpydoc-insertion-style 'yas)
  (setq numpydoc-insert-examples-block nil)
  :bind (:map python-mode-map
	      ("C-c C-n" . numpydoc-generate))
  :after python)

(use-package tree-sitter)
(use-package tree-sitter-langs)
(add-hook 'python-mode-hook 'tree-sitter-mode)
(add-hook 'python-mode-hook #'(lambda () (tree-sitter-hl-mode)))

(use-package yasnippet
  :config (yas-global-mode 1))
(use-package yasnippet-snippets)
(setq yas-snippet-dirs '("~/.emacs.d/snippets"))
```

I really like this package and can't thank you enough for taking the time to write it!

**Comment by douglasdavis** [comment]
I was able to reproduce the issue with the third party tree-sitter package, but with Emacs 29+ built-in tree-sitter support I don't see the issue. I don't have the bandwidth to dig deeper into the problem with the third-party tree-sitter package, but I'd be happy to take a look at any PRs

**Comment by jotafarias13** [comment]
I'm using Emas 28 now and plan to update to Emacs 29 soon, so I guess it won't be a problem for much longer. No need to take any action from my point of view then. Thanks for the clarification!
