### ISSUE TITLE
newlines in templates elided

### ISSUE THREAD

**Issue by nobrowser** [douglasdavis/numpydoc.el#15]
Hi, I'm trying your package on Emacs 28.2. It would be a huge help if I can make it work, and I'm willing to do a lot of configuration. But to start with, I'm hitting this problem that I don't know how to work around: when I execute `numpydoc-generate`, the template outline is inserted correctly, but then when the actual arguments are plugged in the preceding newlines seem to be deleted, or maybe converted to spaces. So it ends up looking like this:

```
"""FIXME: Short description.

FIXME: Long description.

Parameters ---------- uid FIXME: Add docs.

Returns ------- tuple[str, str | None] FIXME: Add docs.

"""
```

It happens regardless which `numpydoc-insertion-style` is in effect - if the prompt style is in effect, it looks fine until I answer the prompt, then it gets mangled. Clearly this negates much of the benefit of the package :(

Thanks for reading,

-- 
Ian

**Comment by nobrowser** [comment]
Update: I am pretty sure this is because of `numpydoc--fill-last-insertion`. Even if it worked correctly, the question is: Why does numpydoc feel it necessary to fill the inserted text? It really seems like too much babysitting. I can see it could be helpful if the prompts are in effect as the response may be too long, but for the bare style it's useless at best.

I can probably fix this for myself with a clever use of advice, but please consider not filling in the bare / manual case.

Also: filling assumes that the fill width (which is usually set with human readable text in mind) is the correct width for python code. In my case that is definitely not true.

**Comment by nobrowser** [comment]
Update 2: Confirmed that advising `numpydoc--fill-last-insertion` to an empty function fixes this for me.

**Comment by douglasdavis** [comment]
Howdy,

> Even if it worked correctly, the question is: Why does numpydoc feel it necessary to fill the inserted text?

Saving some key strokes :)

> It really seems like too much babysitting.

After reading about your use case it seems that it may be  a good idea to make insertion a configurable variable.

**Comment by nobrowser** [comment]
> Howdy,
> 
> > Even if it worked correctly, the question is: Why does numpydoc feel it necessary to fill the inserted text?
> 
> Saving some key strokes :)
> 
> > It really seems like too much babysitting.
> 
> After reading about your use case it seems that it may be a good idea to make `fill-last-insertion` use a configurable variable.

Yes, that would help. Although I am already quite happy with my workaround.

I am guessing that among the small number of people who use Emacs to edit Python, a much smaller slice still uses this package, and I may be close to unique in not liking the prompts. Sigh.

**Comment by douglasdavis** [comment]
`(setq numpydoc-auto-fill-paragraphs nil)` should do the trick. Thanks for raising this!
