### ISSUE TITLE
Incorrect parsing of default values containing commas

### ISSUE THREAD

**Issue by wecassidy** [douglasdavis/numpydoc.el#7]
Minimum working example:
```python
def f(arg="str,str"):
    pass
```
Calling `numpydoc-generate` with point in the function results in the following output:
```python
def f(arg="str,str"):
    """FIXME: Short description.

    FIXME: Long description.

    Parameters
    ----------
    arg : FIXME: Add type.
        FIXME: Add docs.
    str" : FIXME: Add type.
        FIXME: Add docs.

    Examples
    --------
    FIXME: Add docs.

    """
    pass
```
Notice the `str"` in the Parameters section. Similar output occurs with multi-item tuples and sets, but not lists. Dicts fail to generate any documentation with the message `s-trim-right: Wrong type argument: stringp, nil`.

**Comment by douglasdavis** [comment]
Thanks for raising this, I'll try to take a look soon. The set of functions which parse + split the python function signature (`numpydoc--parse-def` and `numpydoc--split-args`) will need some extra logic to handle valid default arguments containing commas.

**Comment by wecassidy** [comment]
Can confirm that #8 fixes the issue. Thanks for responding so quickly!
